version: "3.8"

services:
  postgres:
    image: postgres:14.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: java_db_user
      POSTGRES_PASSWORD: java_db
      POSTGRES_DB: effect_mobile
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/effect_mobile
      SPRING_DATASOURCE_USERNAME: java_db_user
      SPRING_DATASOURCE_PASSWORD: java_db
    depends_on:
      - postgres

volumes:
  postgres_data:
